### ISSUE TITLE
I needed to patch this downstream

### ISSUE THREAD

**Issue by clime** [release-engineering/dist-git#42]
```
-%if 0%{?fedora} || 0%{?rhel} > 7
-Requires:       (dist-git-selinux if selinux-policy-targeted)
-%else
 Requires:       dist-git-selinux
-%endif`
```

Because of koji build error under master: `Dependency tokens must begin with alpha-numeric, '_' or '/': Requires:
(dist-git-selinux if selinux-policy-targeted)"`

**Comment by clime** [comment]
@praiskup any idea about this? :)

**Comment by praiskup** [comment]
Weird, /me is checking.

**Comment by praiskup** [comment]
On what chroots it failed?  I can not find the build failure logs, and epel7 and epel8 seems to build fine locally.

**Comment by praiskup** [comment]
I mean, it looks like an old RPM on Koji builder, but I am not able to reproduce this.

**Comment by praiskup** [comment]
I've seen a different error otoh: https://kojipkgs.fedoraproject.org//work/tasks/7540/52787540/build.log

```
+ cd dist-git-1.16
+ nosetests-3 .
.............E..................E.........
======================================================================
ERROR: test_check_existing_file_with_bad_hash_1_rpms_pkg (test_upload_script.UploadTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/parameterized/parameterized.py", line 392, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/builddir/build/BUILD/dist-git-1.16/tests/test_upload_script.py", line 194, in test_check_existing_file_with_bad_hash
    resp = self.upload(module, hash='abc', filename='hello.txt')
  File "/builddir/build/BUILD/dist-git-1.16/tests/test_upload_script.py", line 159, in upload
    response = requests.post(self.url, data=args, files=files)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /cgi-bin/upload.cgi (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f337cdb1240>: Failed to establish a new connection: [Errno 111] Connection refused',))
-------------------- >> begin captured stdout << ---------------------
```

**Comment by clime** [comment]
Hey, sry, I was doing the release on centos7/epel7 and it was trying to evaluate dist-git.spec which contains rich deps there due to koji NVR check, anyway, will try again now.

**Comment by clime** [comment]
> I've seen a different error otoh: https://kojipkgs.fedoraproject.org//work/tasks/7540/52787540/build.log

Ye, there are some problems with the test suite on epel8. But it's a connection error to the API endpoint rather anything else. The tests should be disabled there for now...thanks.

**Comment by clime** [comment]
Fixed now.

**Comment by praiskup** [comment]
Out of curiosity, I don't see any new commits in history here ... what actually was fixed?

**Comment by clime** [comment]
I patched downstream. Had some troubles during release.

**Comment by clime** [comment]
Thanks a lot for the quick feedback!
