### ISSUE TITLE
FTBFS dist-git in Fedora Rawhide

### ISSUE THREAD

**Issue by praiskup** [release-engineering/dist-git#64]
The test-suite fails:

```Creating /tmp/tmppbkk88hn/new.txt
b'127.0.0.1 - - [18/Jun/2024 08:17:22] "POST /cgi-bin/upload.cgi HTTP/1.1" 200 -\nTraceback (most recent call last):\n  File "/tmp/tmppbkk88hn/cgi-bin/upload.cgi", line 9, in <module>\n    import cgi\nModuleNotFoundError: No module named \'cgi\'\n127.0.0.1 - - [18/Jun/2024 08:17:22] CGI script exit code 1\n'
_______________ UploadTest.test_accepts_sha_512_hash_1_rpms_pkg ________________

a = (<test_upload_script.UploadTest testMethod=test_accepts_sha_512_hash_1_rpms_pkg>,)
kw = {}

    @wraps(func)
    def standalone_func(*a, **kw):
>       return func(*(a + p.args), **p.kwargs, **kw)

/usr/lib/python3.13/site-packages/parameterized/parameterized.py:620: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/test_upload_script.py:233: in test_accepts_sha_512_hash
    self.assertEqual(resp, 'File new.txt size 7 SHA512 %s stored OK\n' % NEW_SHA512)
E   AssertionError: '' != 'File new.txt size 7 SHA512 d3d67bc3e38489[122 chars]OK\n'
E   + File new.txt size 7 SHA512 d3d67bc3e3848925892de9b132c9ff4054a05c9dbc7b4366d16b5c6b87c898df60da162e9ec415d4dc16470128ef52c11c44fc06da2841543ddeb351b10e9fb2 stored OK
```

Python has been updated to 3.13 in Rawhide, might be related.

**Comment by FrostyX** [comment]
Relevant BZ https://bugzilla.redhat.com/show_bug.cgi?id=2300623

**Comment by xsuchy** [comment]
The culprint is few lines below:
```
b'127.0.0.1 - - [31/Jul/2024 15:37:26] "POST /cgi-bin/upload.cgi HTTP/1.1" 200 -\nTraceback (most recent call last):\n  File "/tmp/tmpp3qnpihq/cgi-bin/upload.cgi", line 9, in <module>\n    import cgi\nModuleNotFoundError: No module named \'cgi\'\n127.0.0.1 - - [31/Jul/2024 15:37:26] CGI script exit code 1\n'
```
On my F40:
```
$ python
Python 3.12.4 (main, Jun  7 2024, 00:00:00) [GCC 14.1.1 20240607 (Red Hat 14.1.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cgi
<stdin>:1: DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
```
And F41 has Python 3.13.

**Comment by xsuchy** [comment]
I think we will have to use https://src.fedoraproject.org/rpms/python-multipart
